// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using cima.Settings;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace cima.Settings;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ISiteSettingsAppService), typeof(SiteSettingsClientProxy))]
public partial class SiteSettingsClientProxy : ClientProxyBase<ISiteSettingsAppService>, ISiteSettingsAppService
{
    public virtual async Task<SiteSettingsDto> GetAsync()
    {
        return await RequestAsync<SiteSettingsDto>(nameof(GetAsync));
    }

    public virtual async Task<PublicSiteSettingsDto> GetPublicAsync()
    {
        return await RequestAsync<PublicSiteSettingsDto>(nameof(GetPublicAsync));
    }

    public virtual async Task UpdateEmailSettingsAsync(UpdateEmailSettingsDto input)
    {
        await RequestAsync(nameof(UpdateEmailSettingsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(UpdateEmailSettingsDto), input }
        });
    }

    public virtual async Task UpdateWhatsAppSettingsAsync(UpdateWhatsAppSettingsDto input)
    {
        await RequestAsync(nameof(UpdateWhatsAppSettingsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(UpdateWhatsAppSettingsDto), input }
        });
    }

    public virtual async Task UpdateBusinessInfoAsync(UpdateBusinessInfoDto input)
    {
        await RequestAsync(nameof(UpdateBusinessInfoAsync), new ClientProxyRequestTypeValue
        {
            { typeof(UpdateBusinessInfoDto), input }
        });
    }

    public virtual async Task<bool> TestEmailAsync(TestEmailSettingsDto input)
    {
        return await RequestAsync<bool>(nameof(TestEmailAsync), new ClientProxyRequestTypeValue
        {
            { typeof(TestEmailSettingsDto), input }
        });
    }
}
