// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using cima.ContactRequests;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace cima.ContactRequests;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IContactRequestAppService), typeof(ContactRequestClientProxy))]
public partial class ContactRequestClientProxy : ClientProxyBase<IContactRequestAppService>, IContactRequestAppService
{
    public virtual async Task<ContactRequestDto> CreateAsync(CreateContactRequestDto input)
    {
        return await RequestAsync<ContactRequestDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CreateContactRequestDto), input }
        });
    }

    public virtual async Task<PagedResultDto<ContactRequestDto>> GetListAsync(int skipCount, int maxResultCount)
    {
        return await RequestAsync<PagedResultDto<ContactRequestDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(int), skipCount },
            { typeof(int), maxResultCount }
        });
    }

    public virtual async Task<PagedResultDto<ContactRequestDto>> GetByArchitectAsync(Guid architectId, int skipCount, int maxResultCount)
    {
        return await RequestAsync<PagedResultDto<ContactRequestDto>>(nameof(GetByArchitectAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), architectId },
            { typeof(int), skipCount },
            { typeof(int), maxResultCount }
        });
    }

    public virtual async Task<ContactRequestDto> MarkAsRepliedAsync(Guid id, MarkAsRepliedDto input)
    {
        return await RequestAsync<ContactRequestDto>(nameof(MarkAsRepliedAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(MarkAsRepliedDto), input }
        });
    }

    public virtual async Task<ContactRequestDto> CloseAsync(Guid id)
    {
        return await RequestAsync<ContactRequestDto>(nameof(CloseAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ContactRequestDto> GetAsync(Guid id)
    {
        return await RequestAsync<ContactRequestDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
