// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace cima.Architects;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IArchitectAppService), typeof(ArchitectClientProxy))]
public partial class ArchitectClientProxy : ClientProxyBase<IArchitectAppService>, IArchitectAppService
{
    public virtual async Task<PagedResultDto<ArchitectDto>> GetListAsync(
        PagedAndSortedResultRequestDto input,
        CancellationToken cancellationToken = default)
    {
        return await RequestAsync<PagedResultDto<ArchitectDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input }
        });
    }

    public virtual async Task<ArchitectDto> GetAsync(Guid id, CancellationToken cancellationToken = default)
    {
        return await RequestAsync<ArchitectDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ArchitectDto> GetByUserIdAsync(Guid userId, CancellationToken cancellationToken = default)
    {
        return await RequestAsync<ArchitectDto>(nameof(GetByUserIdAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), userId }
        });
    }

    public virtual async Task<ArchitectDto> CreateAsync(CreateArchitectDto input, CancellationToken cancellationToken = default)
    {
        return await RequestAsync<ArchitectDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CreateArchitectDto), input }
        });
    }

    public virtual async Task<ArchitectDto> UpdateAsync(Guid id, UpdateArchitectDto input, CancellationToken cancellationToken = default)
    {
        return await RequestAsync<ArchitectDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(UpdateArchitectDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id, CancellationToken cancellationToken = default)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
