// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
#nullable enable
using cima.Architects;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace cima.Architects;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IArchitectAppService), typeof(ArchitectClientProxy))]
public partial class ArchitectClientProxy : ClientProxyBase<IArchitectAppService>, IArchitectAppService
{
    public virtual async Task<PagedResultDto<ArchitectDto>> GetListAsync(PagedAndSortedResultRequestDto input, CancellationToken cancellationToken)
    {
        return await RequestAsync<PagedResultDto<ArchitectDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedResultRequestDto), input },
            { typeof(CancellationToken), cancellationToken }
        });
    }

    public virtual async Task<ArchitectDto> GetAsync(Guid id, CancellationToken cancellationToken)
    {
        return await RequestAsync<ArchitectDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(CancellationToken), cancellationToken }
        });
    }

    public virtual async Task<ArchitectDto> GetByUserIdAsync(Guid userId, CancellationToken cancellationToken)
    {
        return await RequestAsync<ArchitectDto>(nameof(GetByUserIdAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), userId },
            { typeof(CancellationToken), cancellationToken }
        });
    }

    public virtual async Task<ArchitectDto?> GetCurrentAsync(CancellationToken cancellationToken)
    {
        return await RequestAsync<ArchitectDto?>(nameof(GetCurrentAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CancellationToken), cancellationToken }
        });
    }

    public virtual async Task<CreateArchitectResultDto> CreateWithUserAsync(CreateArchitectWithUserDto input, CancellationToken cancellationToken)
    {
        return await RequestAsync<CreateArchitectResultDto>(nameof(CreateWithUserAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CreateArchitectWithUserDto), input },
            { typeof(CancellationToken), cancellationToken }
        });
    }

    public virtual async Task<ArchitectDto> CreateAsync(CreateArchitectDto input, CancellationToken cancellationToken)
    {
        return await RequestAsync<ArchitectDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CreateArchitectDto), input },
            { typeof(CancellationToken), cancellationToken }
        });
    }

    public virtual async Task<ArchitectDto> UpdateAsync(Guid id, UpdateArchitectDto input, CancellationToken cancellationToken)
    {
        return await RequestAsync<ArchitectDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(UpdateArchitectDto), input },
            { typeof(CancellationToken), cancellationToken }
        });
    }

    public virtual async Task DeleteAsync(Guid id, CancellationToken cancellationToken)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(CancellationToken), cancellationToken }
        });
    }

    public virtual async Task<string> ResetPasswordAsync(Guid id, ResetArchitectPasswordDto input, CancellationToken cancellationToken)
    {
        return await RequestAsync<string>(nameof(ResetPasswordAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(ResetArchitectPasswordDto), input },
            { typeof(CancellationToken), cancellationToken }
        });
    }

    public virtual async Task ChangePasswordAsync(ChangeArchitectPasswordDto input, CancellationToken cancellationToken)
    {
        await RequestAsync(nameof(ChangePasswordAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ChangeArchitectPasswordDto), input },
            { typeof(CancellationToken), cancellationToken }
        });
    }

    public virtual async Task<bool> MustChangePasswordAsync(CancellationToken cancellationToken)
    {
        return await RequestAsync<bool>(nameof(MustChangePasswordAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CancellationToken), cancellationToken }
        });
    }
}
