// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using cima.Listings;
using cima.Listings.Outputs;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace cima.Listings;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IFeaturedListingAppService), typeof(FeaturedListingClientProxy))]
public partial class FeaturedListingClientProxy : ClientProxyBase<IFeaturedListingAppService>, IFeaturedListingAppService
{
    public virtual async Task<List<FeaturedListingDto>> GetAllAsync()
    {
        return await RequestAsync<List<FeaturedListingDto>>(nameof(GetAllAsync));
    }

    public virtual async Task<PagedResultDto<FeaturedListingDto>> GetPagedAsync(GetFeaturedListingsDto input)
    {
        return await RequestAsync<PagedResultDto<FeaturedListingDto>>(nameof(GetPagedAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetFeaturedListingsDto), input }
        });
    }

    public virtual async Task<List<ListingSummaryDto>> GetForHomepageAsync(int count)
    {
        return await RequestAsync<List<ListingSummaryDto>>(nameof(GetForHomepageAsync), new ClientProxyRequestTypeValue
        {
            { typeof(int), count }
        });
    }

    public virtual async Task<FeaturedListingDto> AddAsync(CreateFeaturedListingDto input)
    {
        return await RequestAsync<FeaturedListingDto>(nameof(AddAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CreateFeaturedListingDto), input }
        });
    }

    public virtual async Task RemoveAsync(Guid featuredListingId)
    {
        await RequestAsync(nameof(RemoveAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), featuredListingId }
        });
    }

    public virtual async Task RemoveByListingIdAsync(Guid listingId)
    {
        await RequestAsync(nameof(RemoveByListingIdAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), listingId }
        });
    }

    public virtual async Task<bool> IsListingFeaturedAsync(Guid listingId)
    {
        return await RequestAsync<bool>(nameof(IsListingFeaturedAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), listingId }
        });
    }

    public virtual async Task<int> GetCountAsync()
    {
        return await RequestAsync<int>(nameof(GetCountAsync));
    }
}
