// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using cima.Listings;
using cima.Listings.Inputs;
using cima.Listings.Outputs;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace cima.Listings;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IListingAppService), typeof(ListingClientProxy))]
public partial class ListingClientProxy : ClientProxyBase<IListingAppService>, IListingAppService
{
    public virtual async Task<PagedResultDto<ListingSummaryDto>> GetListAsync(GetListingsInput input)
    {
        return await RequestAsync<PagedResultDto<ListingSummaryDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetListingsInput), input }
        });
    }

    public virtual async Task<ListingDetailDto> GetAsync(Guid id)
    {
        return await RequestAsync<ListingDetailDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ListingDetailDto> CreateAsync(CreateListingDto input)
    {
        return await RequestAsync<ListingDetailDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CreateListingDto), input }
        });
    }

    public virtual async Task<ListingDetailDto> UpdateAsync(Guid id, UpdateListingDto input)
    {
        return await RequestAsync<ListingDetailDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(UpdateListingDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ListingDetailDto> PublishAsync(PublishListingDto input)
    {
        return await RequestAsync<ListingDetailDto>(nameof(PublishAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PublishListingDto), input }
        });
    }

    public virtual async Task<ListingDetailDto> ArchiveAsync(Guid id)
    {
        return await RequestAsync<ListingDetailDto>(nameof(ArchiveAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ListingDetailDto> UnarchiveAsync(Guid id)
    {
        return await RequestAsync<ListingDetailDto>(nameof(UnarchiveAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ListingDetailDto> UnpublishAsync(Guid id)
    {
        return await RequestAsync<ListingDetailDto>(nameof(UnpublishAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ListingDetailDto> MoveToPortfolioAsync(Guid id)
    {
        return await RequestAsync<ListingDetailDto>(nameof(MoveToPortfolioAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ListingDetailDto> DuplicateAsync(Guid id)
    {
        return await RequestAsync<ListingDetailDto>(nameof(DuplicateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PagedResultDto<ListingSummaryDto>> GetPublishedAsync(GetListingsInput input)
    {
        return await RequestAsync<PagedResultDto<ListingSummaryDto>>(nameof(GetPublishedAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetListingsInput), input }
        });
    }

    public virtual async Task<PagedResultDto<ListingSummaryDto>> GetByArchitectAsync(Guid architectId, int skipCount, int maxResultCount)
    {
        return await RequestAsync<PagedResultDto<ListingSummaryDto>>(nameof(GetByArchitectAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), architectId },
            { typeof(int), skipCount },
            { typeof(int), maxResultCount }
        });
    }

    public virtual async Task<ListingImageDto> AddImageAsync(AddListingImageDto input)
    {
        return await RequestAsync<ListingImageDto>(nameof(AddImageAsync), new ClientProxyRequestTypeValue
        {
            { typeof(AddListingImageDto), input }
        });
    }

    public virtual async Task RemoveImageAsync(Guid listingId, Guid imageId)
    {
        await RequestAsync(nameof(RemoveImageAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), listingId },
            { typeof(Guid), imageId }
        });
    }

    public virtual async Task UpdateImagesOrderAsync(Guid listingId, List<UpdateImageOrderDto> input)
    {
        await RequestAsync(nameof(UpdateImagesOrderAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), listingId },
            { typeof(List<UpdateImageOrderDto>), input }
        });
    }

    public virtual async Task<PagedResultDto<ListingSummaryDto>> SearchAsync(PropertySearchDto searchDto)
    {
        return await RequestAsync<PagedResultDto<ListingSummaryDto>>(nameof(SearchAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PropertySearchDto), searchDto }
        });
    }

    public virtual async Task<PagedResultDto<ListingSummaryDto>> GetPortfolioAsync(GetListingsInput input)
    {
        return await RequestAsync<PagedResultDto<ListingSummaryDto>>(nameof(GetPortfolioAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetListingsInput), input }
        });
    }

    public virtual async Task<List<LocationSuggestionDto>> GetLocationSuggestionsAsync(string searchTerm)
    {
        return await RequestAsync<List<LocationSuggestionDto>>(nameof(GetLocationSuggestionsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), searchTerm }
        });
    }
}
