// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using cima.Domain.Shared.Dtos;
using cima.Listings;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace cima.Listings;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IListingAppService), typeof(ListingClientProxy))]
public partial class ListingClientProxy : ClientProxyBase<IListingAppService>, IListingAppService
{
    public virtual async Task<PagedResultDto<ListingDto>> GetListAsync(GetListingsInput input)
    {
        return await RequestAsync<PagedResultDto<ListingDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetListingsInput), input }
        });
    }

    public virtual async Task<ListingDto> GetAsync(Guid id)
    {
        return await RequestAsync<ListingDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ListingDto> CreateAsync(CreateUpdateListingDto input)
    {
        return await RequestAsync<ListingDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CreateUpdateListingDto), input }
        });
    }

    public virtual async Task<ListingDto> UpdateAsync(Guid id, CreateUpdateListingDto input)
    {
        return await RequestAsync<ListingDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(CreateUpdateListingDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ListingDto> PublishAsync(Guid id)
    {
        return await RequestAsync<ListingDto>(nameof(PublishAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ListingDto> ArchiveAsync(Guid id)
    {
        return await RequestAsync<ListingDto>(nameof(ArchiveAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ListingDto> UnarchiveAsync(Guid id)
    {
        return await RequestAsync<ListingDto>(nameof(UnarchiveAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ListingDto> UnpublishAsync(Guid id)
    {
        return await RequestAsync<ListingDto>(nameof(UnpublishAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PagedResultDto<ListingDto>> GetPublishedAsync(GetListingsInput input)
    {
        return await RequestAsync<PagedResultDto<ListingDto>>(nameof(GetPublishedAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetListingsInput), input }
        });
    }

    public virtual async Task<PagedResultDto<ListingDto>> GetByArchitectAsync(Guid architectId, int skipCount, int maxResultCount)
    {
        return await RequestAsync<PagedResultDto<ListingDto>>(nameof(GetByArchitectAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), architectId },
            { typeof(int), skipCount },
            { typeof(int), maxResultCount }
        });
    }

    public virtual async Task<ListingImageDto> AddImageAsync(Guid listingId, CreateListingImageDto input)
    {
        return await RequestAsync<ListingImageDto>(nameof(AddImageAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), listingId },
            { typeof(CreateListingImageDto), input }
        });
    }

    public virtual async Task RemoveImageAsync(Guid listingId, Guid imageId)
    {
        await RequestAsync(nameof(RemoveImageAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), listingId },
            { typeof(Guid), imageId }
        });
    }

    public virtual async Task UpdateImagesOrderAsync(Guid listingId, List<UpdateImageOrderDto> input)
    {
        await RequestAsync(nameof(UpdateImagesOrderAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), listingId },
            { typeof(List<UpdateImageOrderDto>), input }
        });
    }
}
