// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace cima.Statistics;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IStatisticsAppService), typeof(StatisticsClientProxy))]
public partial class StatisticsClientProxy : ClientProxyBase<IStatisticsAppService>, IStatisticsAppService
{
    public virtual async Task<DashboardStatsDto> GetDashboardAsync()
    {
        return await RequestAsync<DashboardStatsDto>(nameof(GetDashboardAsync));
    }

    public virtual async Task<ListingStatsDto> GetListingStatsAsync()
    {
        return await RequestAsync<ListingStatsDto>(nameof(GetListingStatsAsync));
    }

    public virtual async Task<ContactRequestStatsDto> GetContactRequestStatsAsync()
    {
        return await RequestAsync<ContactRequestStatsDto>(nameof(GetContactRequestStatsAsync));
    }
}
